// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241004171135_Seeding data for Difficulties and Regions table")]
    partial class SeedingdataforDifficultiesandRegionstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fe4ea12-a184-45de-9db5-dc93b19fb886"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("f2537da4-04ce-4b4f-805a-24f7862ac43e"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("290aa1b6-4d23-44cd-94a7-0a5c5d18dbbb"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75f98dfc-8892-4586-a7da-78a545d1c40b"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://test.com/wellington.jpg"
                        },
                        new
                        {
                            Id = new Guid("f7bfb5cf-7919-4c90-9b4d-91de354b4c11"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://test.com/auckland.jpg"
                        },
                        new
                        {
                            Id = new Guid("9a5b58c1-d91a-47e3-8101-c03c2f839adf"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://test.com/christchurch.jpg"
                        },
                        new
                        {
                            Id = new Guid("a4e65b12-c0c3-4bb4-bb4d-1fd61ef6358f"),
                            Code = "HAM",
                            Name = "Hamilton",
                            RegionImageUrl = "https://test.com/hamilton.jpg"
                        },
                        new
                        {
                            Id = new Guid("5a8ef127-82b4-4721-8d65-6f769eef2b56"),
                            Code = "DUD",
                            Name = "Dunedin",
                            RegionImageUrl = "https://test.com/dunedin.jpg"
                        },
                        new
                        {
                            Id = new Guid("dd6f96c3-fbc6-4b43-b89b-8f626d0e18f6"),
                            Code = "QTN",
                            Name = "Queenstown",
                            RegionImageUrl = "https://test.com/queenstown.jpg"
                        },
                        new
                        {
                            Id = new Guid("cfb8f37c-4a45-4cbf-a8ba-11fefdfdfedd"),
                            Code = "RTR",
                            Name = "Rotorua",
                            RegionImageUrl = "https://test.com/rotorua.jpg"
                        },
                        new
                        {
                            Id = new Guid("93f7a19c-2e65-4db8-8c6e-0dd25c7bf93d"),
                            Code = "NPR",
                            Name = "Napier",
                            RegionImageUrl = "https://test.com/napier.jpg"
                        },
                        new
                        {
                            Id = new Guid("e6c4e032-6a19-432b-9466-cc342a7558de"),
                            Code = "TRG",
                            Name = "Tauranga",
                            RegionImageUrl = "https://test.com/tauranga.jpg"
                        },
                        new
                        {
                            Id = new Guid("1b27e9b2-5c2b-49db-9b12-5a36dbd2b789"),
                            Code = "IVC",
                            Name = "Invercargill",
                            RegionImageUrl = "https://test.com/invercargill.jpg"
                        },
                        new
                        {
                            Id = new Guid("b27e9b54-6893-4f5d-83e8-4ad6b4cfae7c"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://test.com/nelson.jpg"
                        },
                        new
                        {
                            Id = new Guid("8d5e786b-cc43-4b6f-9a6f-c49a4fdfd223"),
                            Code = "PMR",
                            Name = "Palmerston North",
                            RegionImageUrl = "https://test.com/palmerstonnorth.jpg"
                        },
                        new
                        {
                            Id = new Guid("31c1a2d2-21bc-4b4d-b71b-41f30353aecd"),
                            Code = "NPL",
                            Name = "New Plymouth",
                            RegionImageUrl = "https://test.com/newplymouth.jpg"
                        },
                        new
                        {
                            Id = new Guid("c0f1f364-65d6-4f87-96a4-0a2a9783b6c4"),
                            Code = "WHG",
                            Name = "Whangarei",
                            RegionImageUrl = "https://test.com/whangarei.jpg"
                        },
                        new
                        {
                            Id = new Guid("d4f7db27-8d6e-4502-912f-f9a61b5d5894"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://test.com/gisborne.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
