// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241004172948_SeedNewData")]
    partial class SeedNewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5d22f24-d5c4-4b65-8b8e-16447bfa4381"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("cc6c55d7-6d9f-40a1-9c9e-8e94e1e5e9bc"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("b9b1dabc-dcdc-4b06-b594-b0c4301a5e8d"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7e98812-a5bc-4c97-8d1a-61f8d4a9f6ef"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://test.com/images/wellington.jpg"
                        },
                        new
                        {
                            Id = new Guid("e97a3b1e-fc2a-4739-91a3-6c04f09d26b2"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://test.com/images/auckland.jpg"
                        },
                        new
                        {
                            Id = new Guid("8c9a74c6-9c90-4b3a-97d5-88a9d70d22f1"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://test.com/images/christchurch.jpg"
                        },
                        new
                        {
                            Id = new Guid("c6f1e32c-7a32-4b2e-b7e5-9bcbf7efcb4a"),
                            Code = "HAM",
                            Name = "Hamilton",
                            RegionImageUrl = "https://test.com/images/hamilton.jpg"
                        },
                        new
                        {
                            Id = new Guid("58e5d0f1-659f-42b4-8b69-bfdcb4708fa5"),
                            Code = "DUD",
                            Name = "Dunedin",
                            RegionImageUrl = "https://test.com/images/dunedin.jpg"
                        },
                        new
                        {
                            Id = new Guid("6c0fda6e-555e-4c2d-9d34-412342b74bc2"),
                            Code = "QTN",
                            Name = "Queenstown",
                            RegionImageUrl = "https://test.com/images/queenstown.jpg"
                        },
                        new
                        {
                            Id = new Guid("b61bbcb7-5f43-4e38-9050-15f178e8d4a5"),
                            Code = "RTR",
                            Name = "Rotorua",
                            RegionImageUrl = "https://test.com/images/rotorua.jpg"
                        },
                        new
                        {
                            Id = new Guid("ec0f60a1-63f8-4901-a63c-0075f812dbf3"),
                            Code = "NPR",
                            Name = "Napier-Hastings",
                            RegionImageUrl = "https://test.com/images/napier.jpg"
                        },
                        new
                        {
                            Id = new Guid("16cf9c45-1004-4f04-85bb-bd3ff9a317c3"),
                            Code = "TRG",
                            Name = "Tauranga",
                            RegionImageUrl = "https://test.com/images/tauranga.jpg"
                        },
                        new
                        {
                            Id = new Guid("b69b69c3-8243-4b66-b3c5-4e2dfd0a8cc6"),
                            Code = "IVC",
                            Name = "Invercargill",
                            RegionImageUrl = "https://test.com/images/invercargill.jpg"
                        },
                        new
                        {
                            Id = new Guid("fe0b0053-5a7d-49a1-8a38-ea37d4b00725"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://test.com/images/nelson.jpg"
                        },
                        new
                        {
                            Id = new Guid("a30dbd93-1e53-46b4-9c63-f0eabf9cfed2"),
                            Code = "PMR",
                            Name = "Palmerston North",
                            RegionImageUrl = "https://test.com/images/palmerstonnorth.jpg"
                        },
                        new
                        {
                            Id = new Guid("d0c7f3d2-0370-479f-9c09-98f4e09a2b62"),
                            Code = "NPL",
                            Name = "New Plymouth",
                            RegionImageUrl = "https://test.com/images/newplymouth.jpg"
                        },
                        new
                        {
                            Id = new Guid("d55c0882-2436-4b93-9e48-16f6c8df73bb"),
                            Code = "WHG",
                            Name = "Whangarei",
                            RegionImageUrl = "https://test.com/images/whangarei.jpg"
                        },
                        new
                        {
                            Id = new Guid("5ee09c8b-8f41-4c9f-bf99-6cf37426e0aa"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://test.com/images/gisborne.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
